.TH "iBleibFit/cbleibfitplugin.cpp" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iBleibFit/cbleibfitplugin.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cbleibfitplugin\&.h'\fP
.br
\fC#include <QNetworkAccessManager>\fP
.br
\fC#include <QNetworkRequest>\fP
.br
\fC#include <QNetworkReply>\fP
.br
\fC#include <QEventLoop>\fP
.br
\fC#include <QMessageBox>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtagMAPPER\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBtagMAPPER\fP \fBMAPPER\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMAPPER\fP \fBg_ingredientMapper\fP []"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBtagMAPPER\fP	 \fBMAPPER\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBMAPPER\fP g_ingredientMapper[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
