.TH "dMySQL/cconfigdialog.cpp" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dMySQL/cconfigdialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cconfigdialog\&.h'\fP
.br
\fC#include 'ui_cconfigdialog\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QCloseEvent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
