.TH "dMySQL/cconfigdialog.h" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dMySQL/cconfigdialog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QCloseEvent>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcConfigDialog\fP"
.br
.RI "\fIConfiguration Dialog for dMySQL\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
