.TH "iErnaehrung/cernaehrungplugin.cpp" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iErnaehrung/cernaehrungplugin.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cernaehrungplugin\&.h'\fP
.br
\fC#include <QNetworkAccessManager>\fP
.br
\fC#include <QNetworkRequest>\fP
.br
\fC#include <QNetworkReply>\fP
.br
\fC#include <QEventLoop>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QTextDocument>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtagVALUES\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBtagVALUES\fP \fBVALUES\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBtoValue\fP (const QString &sz)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBVALUES\fP \fBg_values\fP []"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBtagVALUES\fP  \fBVALUES\fP"

.SH "Function Documentation"
.PP 
.SS "double toValue (const QString & sz)"

.PP
Referenced by cErnaehrungPlugin::load()\&.
.SH "Variable Documentation"
.PP 
.SS "\fBVALUES\fP g_values[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
