.TH "Kooky/cimportinterface.h" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kooky/cimportinterface.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cingredient\&.h'\fP
.br
\fC#include 'cInterface\&.h'\fP
.br
\fC#include <QtPlugin>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QMap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcImportInterface\fP"
.br
.RI "\fIInterface class for importing data\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QT_BEGIN_NAMESPACE \fBQ_DECLARE_INTERFACE\fP (\fBcImportInterface\fP,'WIN\-DESIGN\&.cImportInterface/1\&.0')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QT_BEGIN_NAMESPACE Q_DECLARE_INTERFACE (\fBcImportInterface\fP, 'WIN\-DESIGN\&.cImportInterface/1\&.0')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
