.TH "Kooky/cingredient.h" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kooky/cingredient.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDate>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QDomDocument>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcIngredient\fP"
.br
.RI "\fIThis class holds data of an ingredient\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
