.TH "Kooky/cingredient.cpp" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kooky/cingredient.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cingredient\&.h'\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QXmlStreamWriter>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtagGROUPNAME\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBtagGROUPNAME\fP \fBGROUPNAME\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBGROUPNAME\fP \fBg_groupname\fP []"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBtagGROUPNAME\fP	 \fBGROUPNAME\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBGROUPNAME\fP g_groupname[]\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
