.TH "Kooky/cInterface.h" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kooky/cInterface.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcInterface\fP"
.br
.RI "\fIThis is the base class for all plugins\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
