.TH "Kooky/cmainwindow.h" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kooky/cmainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cplugin\&.h'\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QStandardItemModel>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcMainWindow\fP"
.br
.RI "\fIThis is the class that implements the main window\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
