.TH "Kooky/cmainwindow.cpp" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kooky/cmainwindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cmainwindow\&.h'\fP
.br
\fC#include 'ui_cmainwindow\&.h'\fP
.br
\fC#include 'cimportinterface\&.h'\fP
.br
\fC#include 'cingredient\&.h'\fP
.br
\fC#include 'coptions\&.h'\fP
.br
\fC#include 'cimportingredientdialog\&.h'\fP
.br
\fC#include <QPluginLoader>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QImage>\fP
.br
\fC#include <QContextMenuEvent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
