.TH "cMDIArea" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cMDIArea \- This class overwrites the default MDI area of the main window\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdiarea\&.h>\fP
.SH "Detailed Description"
.PP 
This class overwrites the default MDI area of the main window\&. It also adds the capability to display a background image in the MDI area\&.
.PP
\fBNote:\fP
.RS 4
.RE
.PP
\fBAuthor:\fP
.RS 4
Herwig Birke
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0
.RE
.PP
\fBDate:\fP
.RS 4
2016/02/09 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
