.TH "dMySQL/cmysqlplugin.cpp" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dMySQL/cmysqlplugin.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cmysqlplugin\&.h'\fP
.br
\fC#include 'cconfigdialog\&.h'\fP
.br
\fC#include <QSqlError>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QSqlQuery>\fP
.br
\fC#include <QMessageBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
