.TH "dMySQL/cmysqlplugin.h" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dMySQL/cmysqlplugin.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cdbinterface\&.h'\fP
.br
\fC#include <QtCore>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QSqlDatabase>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcMySQLPlugin\fP"
.br
.RI "\fIMySQL Database Connector Plugin class\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
