.TH "Kooky/coptions.cpp" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kooky/coptions.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'coptions\&.h'\fP
.br
\fC#include 'ui_coptions\&.h'\fP
.br
\fC#include 'coptionsplugins\&.h'\fP
.br
\fC#include <QTreeWidgetItem>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
