.TH "Kooky/coptionsplugins.cpp" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kooky/coptionsplugins.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'coptionsplugins\&.h'\fP
.br
\fC#include 'ui_coptionsplugins\&.h'\fP
.br
\fC#include <QCheckBox>\fP
.br
\fC#include <QSettings>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
