.TH "Kooky/coptions.h" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kooky/coptions.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cmainwindow\&.h'\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QStandardItemModel>\fP
.br
\fC#include <QItemSelection>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcOptions\fP"
.br
.RI "\fIThis dialog displays all options\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
