.TH "Kooky/cplugin.h" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kooky/cplugin.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cimportinterface\&.h'\fP
.br
\fC#include 'cdbinterface\&.h'\fP
.br
\fC#include <QPluginLoader>\fP
.br
\fC#include <QAction>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcPlugin\fP"
.br
.RI "\fIThis class holds data of an plugin\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
