.TH "KOOKY" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KOOKY \- Kooky Main Program
.PP
This is the main program of Kooky\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcDBInterface\fP"
.br
.RI "\fIThis is the base class for all database connector plugins\&. \fP"
.ti -1c
.RI "class \fBcImportIngredientDialog\fP"
.br
.RI "\fIThis dialog imports ingredients based on the selected import plugin\&. \fP"
.ti -1c
.RI "class \fBcImportInterface\fP"
.br
.RI "\fIInterface class for importing data\&. \fP"
.ti -1c
.RI "class \fBcIngredient\fP"
.br
.RI "\fIThis class holds data of an ingredient\&. \fP"
.ti -1c
.RI "class \fBcInterface\fP"
.br
.RI "\fIThis is the base class for all plugins\&. \fP"
.ti -1c
.RI "class \fBcMainWindow\fP"
.br
.RI "\fIThis is the class that implements the main window\&. \fP"
.ti -1c
.RI "class \fBcMDIArea\fP"
.br
.RI "\fIThis class overwrites the default MDI area of the main window\&. \fP"
.ti -1c
.RI "class \fBcMessageAnimateDialog\fP"
.br
.RI "\fIClass to display a modal message dialog\&. \fP"
.ti -1c
.RI "class \fBcOptions\fP"
.br
.RI "\fIThis dialog displays all options\&. \fP"
.ti -1c
.RI "class \fBcOptionsPlugins\fP"
.br
.RI "\fIThis dialog displays all plugins\&. \fP"
.ti -1c
.RI "class \fBcPlugin\fP"
.br
.RI "\fIThis class holds data of an plugin\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
