.TH "iErnaehrung/moc_cernaehrungplugin.cpp" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iErnaehrung/moc_cernaehrungplugin.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cernaehrungplugin\&.h'\fP
.br
\fC#include <QtCore/qbytearray\&.h>\fP
.br
\fC#include <QtCore/qmetatype\&.h>\fP
.br
\fC#include <QtCore/qplugin\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBqt_meta_stringdata_cErnaehrungPlugin_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQT_MOC_LITERAL\fP(idx,  ofs,  len)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const \fBqt_meta_stringdata_cErnaehrungPlugin_t\fP \fBqt_meta_stringdata_cErnaehrungPlugin\fP"
.br
.ti -1c
.RI "static const uint \fBqt_meta_data_cErnaehrungPlugin\fP []"
.br
.ti -1c
.RI "QT_PLUGIN_METADATA_SECTION const uint \fBqt_section_alignment_dummy\fP = 42"
.br
.ti -1c
.RI "static QT_PLUGIN_METADATA_SECTION const unsigned char \fBqt_pluginMetaData\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QT_MOC_LITERAL(idx, ofs, len)"
\fBValue:\fP
.PP
.nf
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_cErnaehrungPlugin_t, stringdata) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
.fi
.SH "Variable Documentation"
.PP 
.SS "const uint qt_meta_data_cErnaehrungPlugin[]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {

 
       7,       
       0,       
       0,    0, 
       0,    0, 
       0,    0, 
       0,    0, 
       0,    0, 
       0,       
       0,       

       0        
}
.fi
.SS "const \fBqt_meta_stringdata_cErnaehrungPlugin_t\fP qt_meta_stringdata_cErnaehrungPlugin\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    {

    },
    "cErnaehrungPlugin\0"
}
.fi
.SS "QT_PLUGIN_METADATA_SECTION const unsigned char qt_pluginMetaData[]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    'Q', 'T', 'M', 'E', 'T', 'A', 'D', 'A', 'T', 'A', ' ', ' ',
    0x71, 0x62, 0x6a, 0x73, 0x01, 0x00, 0x00, 0x00,
    0xb8, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, 0x00,
    0xa4, 0x00, 0x00, 0x00, 0x1b, 0x03, 0x00, 0x00,
    0x03, 0x00, 0x49, 0x49, 0x44, 0x00, 0x00, 0x00,
    0x11, 0x00, 0x63, 0x45, 0x72, 0x6e, 0x61, 0x65,
    0x68, 0x72, 0x75, 0x6e, 0x67, 0x50, 0x6c, 0x75,
    0x67, 0x69, 0x6e, 0x00, 0x95, 0x07, 0x00, 0x00,
    0x08, 0x00, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
    0x74, 0x61, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x24, 0x00, 0x00, 0x00,
    0x14, 0x03, 0x00, 0x00, 0x04, 0x00, 0x4b, 0x65,
    0x79, 0x73, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x0c, 0x00, 0x00, 0x00, 0x9b, 0x0e, 0x00, 0x00,
    0x09, 0x00, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e,
    0x61, 0x6d, 0x65, 0x00, 0x11, 0x00, 0x63, 0x45,
    0x72, 0x6e, 0x61, 0x65, 0x68, 0x72, 0x75, 0x6e,
    0x67, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x00,
    0x31, 0x00, 0x00, 0x00, 0x05, 0x00, 0x64, 0x65,
    0x62, 0x75, 0x67, 0x00, 0x3a, 0x40, 0xa0, 0x00,
    0x07, 0x00, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
    0x6e, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00,
    0x2c, 0x00, 0x00, 0x00, 0x64, 0x00, 0x00, 0x00,
    0x88, 0x00, 0x00, 0x00, 0x94, 0x00, 0x00, 0x00
}
.fi
.SS "QT_PLUGIN_METADATA_SECTION const uint qt_section_alignment_dummy = 42"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
