.TH "MYSQL" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MYSQL \- MySQL Database Connector Plugin
.PP
This module is designed to connect to MySQL Databases\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcConfigDialog\fP"
.br
.RI "\fIConfiguration Dialog for dMySQL\&. \fP"
.ti -1c
.RI "class \fBcMySQLPlugin\fP"
.br
.RI "\fIMySQL Database Connector Plugin class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
