.TH "qt_meta_stringdata_cErnaehrungPlugin_t" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_cErnaehrungPlugin_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArrayData \fBdata\fP [1]"
.br
.ti -1c
.RI "char \fBstringdata\fP [19]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QByteArrayData qt_meta_stringdata_cErnaehrungPlugin_t::data[1]"

.SS "char qt_meta_stringdata_cErnaehrungPlugin_t::stringdata[19]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
