.TH "tagGROUPNAME" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagGROUPNAME \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBszName\fP"
.br
.ti -1c
.RI "QString \fBszGroup\fP"
.br
.ti -1c
.RI "\fBcIngredient::iIngredient\fP \fBiIngredient\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBcIngredient::iIngredient\fP tagGROUPNAME::iIngredient"

.SS "QString tagGROUPNAME::szGroup"

.SS "QString tagGROUPNAME::szName"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
