.TH "tagMAPPER" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagMAPPER \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBkey\fP"
.br
.ti -1c
.RI "qint16 \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QString tagMAPPER::key"

.PP
Referenced by cBleibFitPlugin::load()\&.
.SS "qint16 tagMAPPER::value"

.PP
Referenced by cBleibFitPlugin::load()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
