.TH "tagVALUES" 3 "Thu Feb 11 2016" "Kooky" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagVALUES \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBszSearch\fP"
.br
.ti -1c
.RI "\fBcIngredient::iIngredient\fP \fBiIngredient\fP"
.br
.ti -1c
.RI "qreal \fBdValue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "qreal tagVALUES::dValue"

.PP
Referenced by cErnaehrungPlugin::load(), and cErnaehrungPlugin::value()\&.
.SS "\fBcIngredient::iIngredient\fP tagVALUES::iIngredient"

.PP
Referenced by cErnaehrungPlugin::value()\&.
.SS "QString tagVALUES::szSearch"

.PP
Referenced by cErnaehrungPlugin::load()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Kooky from the source code\&.
