Kooky: cSQLitePlugin Class Reference
cSQLitePlugin Class Reference
#include <csqliteplugin.h>
Public Member Functions
qint16 pluginAPIVersion ()
QString pluginName ()
qint16 pluginVersion ()
iType pluginType ()
bool connect ()
bool init ()
QString lastError ()
bool config ()
Public Member Functions inherited from cDBInterface
cDBInterface ()
Constructor.
virtual ~cDBInterface ()
Destructor.
bool connected ()
Returns the current connection status.
QString lastError ()
Returns the last error message of the last operation.
Protected Member Functions
bool open ()
Protected Attributes
QSqlDatabase m_db
QString m_szLastError
Protected Attributes inherited from cDBInterface
bool m_bConnected
Additional Inherited Members
Public Types inherited from cInterface
enum iType { iTypeImport = 0, iTypeExport = 1, iTypeDB = 2 }
Defines the type of the interface.
Member Function Documentation
bool cSQLitePlugin::config () virtual
Returns
bool
Implements cInterface.
Referenced by pluginType().
bool cSQLitePlugin::connect () virtual
Returns
bool
Implements cDBInterface.
References m_db, open(), and pluginName().
Referenced by pluginType().
bool cSQLitePlugin::init () virtual
Returns
bool
Implements cDBInterface.
References cDBInterface::m_bConnected, m_db, m_szLastError, and pluginName().
Referenced by pluginType().
QString cSQLitePlugin::lastError ()
Returns
QString
References m_szLastError.
Referenced by pluginType().
bool cSQLitePlugin::open () protected
Returns
bool
References cDBInterface::m_bConnected, m_db, and m_szLastError.
Referenced by connect(), and pluginType().
qint16 cSQLitePlugin::pluginAPIVersion () inline virtual
Returns
qint16
Implements cInterface.
QString cSQLitePlugin::pluginName () inline virtual
Returns
QString
Implements cInterface.
Referenced by connect(), and init().
iType cSQLitePlugin::pluginType () inline virtual
Returns
iType
Implements cInterface.
References config(), connect(), init(), cInterface::iTypeDB, lastError(), and open().
qint16 cSQLitePlugin::pluginVersion () inline virtual
Returns
qint16
Implements cInterface.
Member Data Documentation
QSqlDatabase cSQLitePlugin::m_db protected
TODO: describe
Referenced by connect(), init(), and open().
QString cSQLitePlugin::m_szLastError protected
TODO: describe
Referenced by init(), lastError(), and open().
The documentation for this class was generated from the following files:
dSQLite/csqliteplugin.h
dSQLite/csqliteplugin.cpp