Kooky: cMainWindow Class Reference
cMainWindow Class Reference
Kooky Main Program
This is the class that implements the main window.
#include <cmainwindow.h>
Public Member Functions
cMainWindow (QWidget *parent=0)
Constructor.
~cMainWindow ()
Destructor.
QList< cPlugin * > pluginList ()
Returns the list of loaded plugins.
Private Slots
void pluginImportTriggered ()
Testing of import trigger raised by import plugins.
void pluginExportTriggered ()
Testing of export trigger raised by export plugins.
void pluginDBTriggered ()
Testing of database trigger raised by database connector plugins.
void on_m_lpMenu_File_Exit_triggered ()
Menu entry "File -> Exit" triggered.
void on_m_lpMenu_Tools_Options_triggered ()
Menu entry "Tools -> Options" triggered.
void onIngredientsListCustomContextMenu (const QPoint &point)
Custom contest menu of ingredients list has been requested.
void onIngredientsListNew ()
New ingredient has been requested.
void onIngredientsListImport ()
Import of ingredient has been requested.
void onIngredientsListDelete ()
Delete of ingredient has been requested.
void onIngredientsListEdit ()
Edit of ingredient has been requested.
Private Member Functions
void init ()
Initialized main windows.
void initDefaultSettings ()
Initializes default settings for Kooky.
void loadPlugins (const QString &szPluginDir)
Loads plugins in the given path.
cPlugin * plugin (QAction *lpAction)
Finds a plugin with the given action.
Private Attributes
Ui::cMainWindow * ui
QList< cPlugin * > m_pluginList
QStandardItemModel * m_lpIngredientsListModel
QAction * m_lpIngredientsListNew
QAction * m_lpIngredientsListImport
QAction * m_lpIngredientsListDelete
QAction * m_lpIngredientsListEdit
QMenu * m_lpIngredientsListMenu
Detailed Description
This class implements the main window and main functionality of Kooky.
Author
Herwig Birke
Version
1.0
Date
2016/02/09
Constructor & Destructor Documentation
cMainWindow::cMainWindow (QWidget * parent = 0) explicit
Parameters
parent
References init().
cMainWindow::~cMainWindow ()
References m_lpIngredientsListDelete, m_lpIngredientsListEdit, m_lpIngredientsListNew, and ui.
Member Function Documentation
void cMainWindow::init () private
References initDefaultSettings(), loadPlugins(), m_lpIngredientsListDelete, m_lpIngredientsListEdit, m_lpIngredientsListImport, m_lpIngredientsListMenu, m_lpIngredientsListModel, m_lpIngredientsListNew, onIngredientsListCustomContextMenu(), onIngredientsListDelete(), onIngredientsListEdit(), onIngredientsListImport(), onIngredientsListNew(), and ui.
Referenced by cMainWindow().
void cMainWindow::initDefaultSettings () private
Referenced by init().
void cMainWindow::loadPlugins (const QString & szPluginDir) private
Parameters
szPluginDir Path to plugins
References cPlugin::isValid(), m_pluginList, pluginDBTriggered(), pluginExportTriggered(), pluginImportTriggered(), cPlugin::pluginName(), cPlugin::setAction(), and ui.
Referenced by init().
void cMainWindow::on_m_lpMenu_File_Exit_triggered () private slot
void cMainWindow::on_m_lpMenu_Tools_Options_triggered () private slot
void cMainWindow::onIngredientsListCustomContextMenu (const QPoint & point) private slot
Parameters
point Current position of mouse cursor.
References m_lpIngredientsListDelete, m_lpIngredientsListEdit, m_lpIngredientsListMenu, m_lpIngredientsListNew, and ui.
Referenced by init().
void cMainWindow::onIngredientsListDelete () private slot
Referenced by init().
void cMainWindow::onIngredientsListEdit () private slot
Referenced by init().
void cMainWindow::onIngredientsListImport () private slot
References m_pluginList, and cImportIngredientDialog::setPluginList().
Referenced by init().
void cMainWindow::onIngredientsListNew () private slot
Referenced by init().
cPlugin * cMainWindow::plugin (QAction * lpAction) private
Parameters
lpAction Action of the plugin.
Returns
cPlugin Plugin corresponding to the action, NULL if not found.
References m_pluginList.
Referenced by pluginDBTriggered().
void cMainWindow::pluginDBTriggered () private slot
References cInterface::config(), cPlugin::dbInterface(), cDBInterface::init(), plugin(), cInterface::pluginName(), and cPlugin::pluginName().
Referenced by loadPlugins().
void cMainWindow::pluginExportTriggered () private slot
Referenced by loadPlugins().
void cMainWindow::pluginImportTriggered () private slot
Referenced by loadPlugins().
QList< cPlugin * > cMainWindow::pluginList ()
Returns
QList<cPlugin *> List of loaded plugins.
References m_pluginList.
Referenced by cOptions::cOptions().
Member Data Documentation
QAction* cMainWindow::m_lpIngredientsListDelete private
"Delee Ingredient" Action for ingredients context menu
Referenced by init(), onIngredientsListCustomContextMenu(), and ~cMainWindow().
QAction* cMainWindow::m_lpIngredientsListEdit private
"Edit Ingredient" Action for ingredients context menu
Referenced by init(), onIngredientsListCustomContextMenu(), and ~cMainWindow().
QAction* cMainWindow::m_lpIngredientsListImport private
"Import Ingredient" Action for ingredients context menu
Referenced by init().
QMenu* cMainWindow::m_lpIngredientsListMenu private
Context menu for ingredients list
Referenced by init(), and onIngredientsListCustomContextMenu().
QStandardItemModel* cMainWindow::m_lpIngredientsListModel private
standard item model for ingredients list
Referenced by init().
QAction* cMainWindow::m_lpIngredientsListNew private
"New Ingredient" Action for ingredients context menu
Referenced by init(), onIngredientsListCustomContextMenu(), and ~cMainWindow().
QList<cPlugin*> cMainWindow::m_pluginList private
List of loaded plugins
Referenced by loadPlugins(), onIngredientsListImport(), plugin(), and pluginList().
Ui::cMainWindow* cMainWindow::ui private
the main window GUI
Referenced by init(), loadPlugins(), onIngredientsListCustomContextMenu(), and ~cMainWindow().
The documentation for this class was generated from the following files:
Kooky/cmainwindow.h
Kooky/cmainwindow.cpp