Kooky: cOptions Class Reference
cOptions Class Reference
Kooky Main Program
This dialog displays all options.
#include <coptions.h>
Public Member Functions
cOptions (QWidget *parent=0)
~cOptions ()
Protected Member Functions
void init ()
Private Slots
void onOptionsTreeSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Private Attributes
Ui::cOptions * ui
cMainWindow * m_lpMainWindow
QList< cPlugin * > m_pluginList
QStandardItemModel * m_lpOptionsTreeModel
Detailed Description
Note
Author
Herwig Birke
Version
1.0
Date
2016/02/09
Constructor & Destructor Documentation
cOptions::cOptions (QWidget * parent = 0) explicit
Parameters
parent
References init(), m_lpMainWindow, m_lpOptionsTreeModel, m_pluginList, cMainWindow::pluginList(), and ui.
cOptions::~cOptions ()
References ui.
Member Function Documentation
void cOptions::init () protected
References m_lpOptionsTreeModel, onOptionsTreeSelectionChanged(), and ui.
Referenced by cOptions().
void cOptions::onOptionsTreeSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) private slot
Parameters
selected
deselected
References m_lpOptionsTreeModel, m_pluginList, cOptionsPlugins::setPlugins(), and ui.
Referenced by init().
Member Data Documentation
cMainWindow* cOptions::m_lpMainWindow private
TODO: describe
Referenced by cOptions().
QStandardItemModel* cOptions::m_lpOptionsTreeModel private
TODO: describe
Referenced by cOptions(), init(), and onOptionsTreeSelectionChanged().
QList<cPlugin*> cOptions::m_pluginList private
TODO: describe
Referenced by cOptions(), and onOptionsTreeSelectionChanged().
Ui::cOptions* cOptions::ui private
TODO: describe
Referenced by cOptions(), init(), onOptionsTreeSelectionChanged(), and ~cOptions().
The documentation for this class was generated from the following files:
Kooky/coptions.h
Kooky/coptions.cpp