Kooky: cInterface Class Reference
cInterface Class Reference abstract
Kooky Main Program
This is the base class for all plugins.
#include <cInterface.h>
Public Types
enum iType { iTypeImport = 0, iTypeExport = 1, iTypeDB = 2 }
Defines the type of the interface.
Public Member Functions
virtual qint16 pluginAPIVersion ()=0
Returns the version of the API.
virtual QString pluginName ()=0
Returns the name of the plugin.
virtual qint16 pluginVersion ()=0
Version of the plugin.
virtual iType pluginType ()=0
Returns the type of the plugin.
virtual bool config ()=0
Calls the configuration dialog (if any).
Detailed Description
This class implements basic interface functionality for all Kooky plugins. All functions may be overwritten by derriving classes.
Note
Do not subclass this class directly, always use the appropriate subclass: cDBInterface for database connectors, cImportInterface for import plugins and cExportInterface for export plugins.
Author
Herwig Birke
Version
1.0
Date
2016/02/09
Member Enumeration Documentation
enum cInterface::iType
Enumerator
iTypeImport
import plugin
iTypeExport
export plugin
iTypeDB
database connector
Member Function Documentation
virtual bool cInterface::config () pure virtual
Note
This function must be derived by the subclass.
Returns
bool true on success, false otherwise.
Implemented in cMySQLPlugin, cSQLitePlugin, cBleibFitPlugin, and cErnaehrungPlugin.
Referenced by cMainWindow::pluginDBTriggered(), and cOptionsPlugins::showConfigDlg().
virtual qint16 cInterface::pluginAPIVersion () pure virtual
Note
This function must be derived by the subclass.
Returns
qint16 version of the API
Implemented in cMySQLPlugin, cSQLitePlugin, cBleibFitPlugin, and cErnaehrungPlugin.
Referenced by cPlugin::pluginAPIVersion().
virtual QString cInterface::pluginName () pure virtual
Note
This function must be derived by the subclass.
The name must be unique and will also be used to store configuration settings.
Returns
QString name of the plugin.
Implemented in cMySQLPlugin, cSQLitePlugin, cBleibFitPlugin, and cErnaehrungPlugin.
Referenced by cMainWindow::pluginDBTriggered(), and cPlugin::pluginName().
virtual iType cInterface::pluginType () pure virtual
Note
This function must be derived by the subclass.
Returns
iType type of the plugin (see enum iType).
Implemented in cMySQLPlugin, cSQLitePlugin, cBleibFitPlugin, and cErnaehrungPlugin.
virtual qint16 cInterface::pluginVersion () pure virtual
Note
This function must be derived by the subclass.
Returns
qint16 version of the plugin.
Implemented in cMySQLPlugin, cSQLitePlugin, cBleibFitPlugin, and cErnaehrungPlugin.
Referenced by cPlugin::pluginVersion().
The documentation for this class was generated from the following file:
Kooky/cInterface.h