Kooky: cErnaehrungPlugin Class Reference
cErnaehrungPlugin Class Reference
#include <cernaehrungplugin.h>
Public Member Functions
qint16 pluginAPIVersion ()
QString pluginName ()
qint16 pluginVersion ()
iType pluginType ()
bool config ()
QMap< QString, QString > detailsCapability ()
QStringList search (const QString &szSearch, const QString &szDetails=QString(""))
bool load (qint16 iIndex)
qreal value (cIngredient::iIngredient i)
QString ingredientName ()
Public Member Functions inherited from cImportInterface
cImportInterface ()
bool loaded ()
QString valueStr (cIngredient::iIngredient i)
QString name (cIngredient::iIngredient i)
QString group (cIngredient::iIngredient i)
Private Attributes
QStringList m_szUrls
QStringList m_szIngredients
qint16 m_iLoadedIndex
Additional Inherited Members
Public Types inherited from cInterface
enum iType { iTypeImport = 0, iTypeExport = 1, iTypeDB = 2 }
Defines the type of the interface.
Protected Attributes inherited from cImportInterface
bool m_bLoaded
qint16 m_iLoadedIndex
Member Function Documentation
bool cErnaehrungPlugin::config () virtual
Returns
bool
Implements cInterface.
Referenced by pluginType().
QMap< QString, QString > cErnaehrungPlugin::detailsCapability () virtual
Returns
QMap<QString, QString>
Implements cImportInterface.
Referenced by pluginType().
QString cErnaehrungPlugin::ingredientName () virtual
Returns
QString
Implements cImportInterface.
Referenced by pluginType().
bool cErnaehrungPlugin::load (qint16 iIndex) virtual
Parameters
iIndex
Returns
bool
Implements cImportInterface.
References tagVALUES::dValue, tagVALUES::szSearch, and toValue().
Referenced by pluginType().
qint16 cErnaehrungPlugin::pluginAPIVersion () inline virtual
Returns
qint16
Implements cInterface.
QString cErnaehrungPlugin::pluginName () inline virtual
Returns
QString
Implements cInterface.
iType cErnaehrungPlugin::pluginType () inline virtual
Returns
iType
Implements cInterface.
References config(), detailsCapability(), ingredientName(), cInterface::iTypeImport, load(), search(), and value().
qint16 cErnaehrungPlugin::pluginVersion () inline virtual
Returns
qint16
Implements cInterface.
QStringList cErnaehrungPlugin::search (const QString & szSearch, const QString & szDetails = QString("")) virtual
Parameters
szSearch
szDetails
Returns
QStringList
Implements cImportInterface.
Referenced by pluginType().
qreal cErnaehrungPlugin::value (cIngredient::iIngredient i) virtual
Parameters
i
Returns
qreal
Implements cImportInterface.
References tagVALUES::dValue, and tagVALUES::iIngredient.
Referenced by pluginType().
Member Data Documentation
qint16 cErnaehrungPlugin::m_iLoadedIndex private
TODO: describe
QStringList cErnaehrungPlugin::m_szIngredients private
TODO: describe
QStringList cErnaehrungPlugin::m_szUrls private
TODO: describe
The documentation for this class was generated from the following files:
iErnaehrung/cernaehrungplugin.h
iErnaehrung/cernaehrungplugin.cpp