Kooky: cMessageAnimateDialog Class Reference
cMessageAnimateDialog Class Reference
Kooky Main Program
Class to display a modal message dialog.
#include <cmessageanimatedialog.h>
Public Member Functions
cMessageAnimateDialog (QWidget *parent=0)
constructor.
~cMessageAnimateDialog ()
destructor.
void setTitle (const QString &szTitle)
Sets the title of the dialog.
void setMessage (const QString &szMessage)
Sets the message of the dialog.
Protected Attributes
QString m_szMessage
QTimer * m_lpTimer
int m_iCount
int m_iDirection
Private Slots
void update ()
This function is called twice a second to update the displayed message.
Private Attributes
Ui::cMessageAnimateDialog * ui
Detailed Description
Class to display a modal message dialog. Title and message can be configured. The dialog displays the message and adds up to 3 points zwice a second to the message.
Author
Herwig Birke
Version
1.0
Date
$Date: 2016/02/09
Constructor & Destructor Documentation
cMessageAnimateDialog::cMessageAnimateDialog (QWidget * parent = 0) explicit
Parameters
parent
References ui.
cMessageAnimateDialog::~cMessageAnimateDialog ()
References m_lpTimer, and ui.
Member Function Documentation
void cMessageAnimateDialog::setMessage (const QString & szMessage)
Parameters
szMessage Message text
References m_lpTimer, m_szMessage, ui, and update().
Referenced by cImportIngredientDialog::on_m_lpSearchButton_clicked(), and cImportIngredientDialog::onIngredientListSelectionChanged().
void cMessageAnimateDialog::setTitle (const QString & szTitle)
Parameters
szTitle Title text
Referenced by cImportIngredientDialog::on_m_lpSearchButton_clicked(), and cImportIngredientDialog::onIngredientListSelectionChanged().
void cMessageAnimateDialog::update () private slot
References m_iCount, m_iDirection, m_szMessage, and ui.
Referenced by setMessage().
Member Data Documentation
int cMessageAnimateDialog::m_iCount protected
Number of points currently being displayed
Referenced by update().
int cMessageAnimateDialog::m_iDirection protected
Increase / decrease number of points
Referenced by update().
QTimer* cMessageAnimateDialog::m_lpTimer protected
Timer object
Referenced by setMessage(), and ~cMessageAnimateDialog().
QString cMessageAnimateDialog::m_szMessage protected
Message to be displayed
Referenced by setMessage(), and update().
Ui::cMessageAnimateDialog* cMessageAnimateDialog::ui private
User interface of the dialog.
Referenced by cMessageAnimateDialog(), setMessage(), update(), and ~cMessageAnimateDialog().
The documentation for this class was generated from the following files:
Kooky/cmessageanimatedialog.h
Kooky/cmessageanimatedialog.cpp