Kooky: cOptionsPlugins Class Reference
cOptionsPlugins Class Reference
Kooky Main Program
This dialog displays all plugins.
#include <coptionsplugins.h>
Public Member Functions
cOptionsPlugins (QWidget *parent=0)
~cOptionsPlugins ()
void setPlugins (QList< cPlugin * > &plugins)
Protected Member Functions
void init ()
void showConfigDlg (const QModelIndex &index)
Private Slots
void onOptionsPluginTreeSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
void onOptionsPluginTreeDoubleClicked (const QModelIndex &index)
void onOptionsPluginTreePluginToggled (bool b)
void on_m_lpButtonConfigure_clicked ()
Private Attributes
Ui::cOptionsPlugins * ui
QStandardItemModel * m_lpPluginsListModel
Detailed Description
Note
Author
Herwig Birke
Version
1.0
Date
2016/02/09
Constructor & Destructor Documentation
cOptionsPlugins::cOptionsPlugins (QWidget * parent = 0) explicit
Parameters
parent
References init().
cOptionsPlugins::~cOptionsPlugins ()
References ui.
Member Function Documentation
void cOptionsPlugins::init () protected
References m_lpPluginsListModel, onOptionsPluginTreeDoubleClicked(), onOptionsPluginTreeSelectionChanged(), and ui.
Referenced by cOptionsPlugins().
void cOptionsPlugins::on_m_lpButtonConfigure_clicked () private slot
References m_lpPluginsListModel, showConfigDlg(), and ui.
void cOptionsPlugins::onOptionsPluginTreeDoubleClicked (const QModelIndex & index) private slot
Parameters
index
References m_lpPluginsListModel, and showConfigDlg().
Referenced by init().
void cOptionsPlugins::onOptionsPluginTreePluginToggled (bool b) private slot
Parameters
b
References m_lpPluginsListModel, cPlugin::pluginName(), and ui.
Referenced by setPlugins().
void cOptionsPlugins::onOptionsPluginTreeSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) private slot
Parameters
selected
deselected
References ui.
Referenced by init().
void cOptionsPlugins::setPlugins (QList< cPlugin * > & plugins)
Parameters
plugins
References m_lpPluginsListModel, onOptionsPluginTreePluginToggled(), cPlugin::PluginCapDB, cPlugin::PluginCapExport, cPlugin::PluginCapImport, cPlugin::PluginCapNone, and ui.
Referenced by cOptions::onOptionsTreeSelectionChanged().
void cOptionsPlugins::showConfigDlg (const QModelIndex & index) protected
Parameters
index
References cPlugin::capability(), cInterface::config(), cPlugin::dbInterface(), cPlugin::importInterface(), m_lpPluginsListModel, cPlugin::PluginCapDB, cPlugin::PluginCapExport, and cPlugin::PluginCapImport.
Referenced by on_m_lpButtonConfigure_clicked(), and onOptionsPluginTreeDoubleClicked().
Member Data Documentation
QStandardItemModel* cOptionsPlugins::m_lpPluginsListModel private
TODO: describe
Referenced by init(), on_m_lpButtonConfigure_clicked(), onOptionsPluginTreeDoubleClicked(), onOptionsPluginTreePluginToggled(), setPlugins(), and showConfigDlg().
Ui::cOptionsPlugins* cOptionsPlugins::ui private
TODO: describe
Referenced by init(), on_m_lpButtonConfigure_clicked(), onOptionsPluginTreePluginToggled(), onOptionsPluginTreeSelectionChanged(), setPlugins(), and ~cOptionsPlugins().
The documentation for this class was generated from the following files:
Kooky/coptionsplugins.h
Kooky/coptionsplugins.cpp