Kooky: cImportIngredientDialog Class Reference
cImportIngredientDialog Class Reference
Kooky Main Program
This dialog imports ingredients based on the selected import plugin.
#include <cimportingredientdialog.h>
Public Member Functions
cImportIngredientDialog (QWidget *parent=0)
~cImportIngredientDialog ()
void setPluginList (const QList< cPlugin * > pluginList)
Protected Member Functions
QStandardItem * addGroup (const QString &group)
void init ()
void initIngredientList ()
void initIngredientDetails ()
Protected Attributes
QList< cPlugin * > m_pluginList
Private Slots
void on_m_lpSearchButton_clicked ()
void on_m_lpSearchString_textChanged (const QString &arg1)
void onIngredientListSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Private Attributes
Ui::cImportIngredientDialog * ui
QStandardItemModel * m_lpIngredientListModel
QStandardItemModel * m_lpIngredientDetailsModel
Detailed Description
This dialog imports ingredients based on the selected import plugin.
Note
Author
Herwig Birke
Version
1.0
Date
2016/02/09
Constructor & Destructor Documentation
cImportIngredientDialog::cImportIngredientDialog (QWidget * parent = 0) explicit
Parameters
parent
References init().
cImportIngredientDialog::~cImportIngredientDialog ()
References ui.
Member Function Documentation
QStandardItem * cImportIngredientDialog::addGroup (const QString & group) protected
Parameters
group
Returns
QStandardItem
References m_lpIngredientDetailsModel.
Referenced by onIngredientListSelectionChanged().
void cImportIngredientDialog::init () protected
References initIngredientDetails(), initIngredientList(), and ui.
Referenced by cImportIngredientDialog().
void cImportIngredientDialog::initIngredientDetails () protected
References m_lpIngredientDetailsModel, and ui.
Referenced by init().
void cImportIngredientDialog::initIngredientList () protected
References m_lpIngredientListModel, onIngredientListSelectionChanged(), and ui.
Referenced by init().
void cImportIngredientDialog::on_m_lpSearchButton_clicked () private slot
References cPlugin::importInterface(), m_lpIngredientListModel, cImportInterface::search(), cMessageAnimateDialog::setMessage(), cMessageAnimateDialog::setTitle(), and ui.
void cImportIngredientDialog::on_m_lpSearchString_textChanged (const QString & arg1) private slot
References ui.
void cImportIngredientDialog::onIngredientListSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) private slot
Parameters
selected
deselected
References addGroup(), cImportInterface::group(), cIngredient::iIngredientMax, cPlugin::importInterface(), cImportInterface::load(), m_lpIngredientDetailsModel, cImportInterface::name(), cMessageAnimateDialog::setMessage(), cMessageAnimateDialog::setTitle(), ui, cImportInterface::value(), and cImportInterface::valueStr().
Referenced by initIngredientList().
void cImportIngredientDialog::setPluginList (const QList< cPlugin * > pluginList)
Parameters
pluginList
References cPlugin::capability(), m_pluginList, cPlugin::PluginCapImport, cPlugin::pluginName(), and ui.
Referenced by cMainWindow::onIngredientsListImport().
Member Data Documentation
QStandardItemModel* cImportIngredientDialog::m_lpIngredientDetailsModel private
TODO: describe
Referenced by addGroup(), initIngredientDetails(), and onIngredientListSelectionChanged().
QStandardItemModel* cImportIngredientDialog::m_lpIngredientListModel private
TODO: describe
Referenced by initIngredientList(), and on_m_lpSearchButton_clicked().
QList<cPlugin*> cImportIngredientDialog::m_pluginList protected
TODO: describe
Referenced by setPluginList().
Ui::cImportIngredientDialog* cImportIngredientDialog::ui private
TODO: describe
Referenced by init(), initIngredientDetails(), initIngredientList(), on_m_lpSearchButton_clicked(), on_m_lpSearchString_textChanged(), onIngredientListSelectionChanged(), setPluginList(), and ~cImportIngredientDialog().
The documentation for this class was generated from the following files:
Kooky/cimportingredientdialog.h
Kooky/cimportingredientdialog.cpp