Kooky: cPlugin Class Reference
cPlugin Class Reference
Kooky Main Program
This class holds data of an plugin.
#include <cplugin.h>
Public Types
enum PluginCap { PluginCapNone = 0, PluginCapImport = 1, PluginCapExport = 2, PluginCapDB = 3 }
Public Member Functions
cPlugin (const QString &szFile)
~cPlugin ()
bool isValid ()
PluginCap capability ()
QString pluginName ()
qint16 pluginAPIVersion ()
qint16 pluginVersion ()
void setAction (QAction *lpAction)
QAction * action ()
QString pluginFile ()
cImportInterface * importInterface ()
cDBInterface * dbInterface ()
Private Attributes
QPluginLoader * m_lpPluginLoader
cImportInterface * m_lpImportInterface
cDBInterface * m_lpDBInterface
QAction * m_lpAction
Detailed Description
Note
Author
Herwig Birke
Version
1.0
Date
2016/02/09
Member Enumeration Documentation
enum cPlugin::PluginCap
Enumerator
PluginCapNone
PluginCapImport
PluginCapExport
PluginCapDB
Constructor & Destructor Documentation
cPlugin::cPlugin (const QString & szFile)
References m_lpDBInterface, m_lpImportInterface, and m_lpPluginLoader.
cPlugin::~cPlugin ()
References m_lpPluginLoader.
Member Function Documentation
QAction * cPlugin::action ()
Returns
QAction
References m_lpAction.
cPlugin::PluginCap cPlugin::capability ()
Returns
PluginCap
References m_lpDBInterface, m_lpImportInterface, PluginCapDB, PluginCapImport, and PluginCapNone.
Referenced by cImportIngredientDialog::setPluginList(), and cOptionsPlugins::showConfigDlg().
cDBInterface * cPlugin::dbInterface ()
Returns
cDBInterface
References m_lpDBInterface.
Referenced by cMainWindow::pluginDBTriggered(), and cOptionsPlugins::showConfigDlg().
cImportInterface * cPlugin::importInterface ()
Returns
cImportInterface
References m_lpImportInterface.
Referenced by cImportIngredientDialog::on_m_lpSearchButton_clicked(), cImportIngredientDialog::onIngredientListSelectionChanged(), and cOptionsPlugins::showConfigDlg().
bool cPlugin::isValid ()
Returns
bool
References m_lpPluginLoader.
Referenced by cMainWindow::loadPlugins().
qint16 cPlugin::pluginAPIVersion ()
Returns
qint16
References m_lpDBInterface, m_lpImportInterface, and cInterface::pluginAPIVersion().
QString cPlugin::pluginFile ()
Returns
QString
References m_lpPluginLoader.
QString cPlugin::pluginName ()
Returns
QString
References m_lpDBInterface, m_lpImportInterface, and cInterface::pluginName().
Referenced by cMainWindow::loadPlugins(), cOptionsPlugins::onOptionsPluginTreePluginToggled(), cMainWindow::pluginDBTriggered(), and cImportIngredientDialog::setPluginList().
qint16 cPlugin::pluginVersion ()
Returns
qint16
References m_lpDBInterface, m_lpImportInterface, and cInterface::pluginVersion().
void cPlugin::setAction (QAction * lpAction)
Parameters
lpAction
References m_lpAction.
Referenced by cMainWindow::loadPlugins().
Member Data Documentation
QAction* cPlugin::m_lpAction private
TODO: describe
Referenced by action(), and setAction().
cDBInterface* cPlugin::m_lpDBInterface private
TODO: describe
Referenced by capability(), cPlugin(), dbInterface(), pluginAPIVersion(), pluginName(), and pluginVersion().
cImportInterface* cPlugin::m_lpImportInterface private
TODO: describe
Referenced by capability(), cPlugin(), importInterface(), pluginAPIVersion(), pluginName(), and pluginVersion().
QPluginLoader* cPlugin::m_lpPluginLoader private
TODO: describe
Referenced by cPlugin(), isValid(), pluginFile(), and ~cPlugin().
The documentation for this class was generated from the following files:
Kooky/cplugin.h
Kooky/cplugin.cpp