Kooky: cBleibFitPlugin Class Reference
cBleibFitPlugin Class Reference
#include <cbleibfitplugin.h>
Public Member Functions
qint16 pluginAPIVersion ()
QString pluginName ()
qint16 pluginVersion ()
iType pluginType ()
bool config ()
QMap< QString, QString > detailsCapability ()
QStringList search (const QString &szSearch, const QString &szDetails=QString(""))
bool load (qint16 iIndex)
qreal value (cIngredient::iIngredient i)
QString ingredientName ()
Public Member Functions inherited from cImportInterface
cImportInterface ()
bool loaded ()
QString valueStr (cIngredient::iIngredient i)
QString name (cIngredient::iIngredient i)
QString group (cIngredient::iIngredient i)
Private Attributes
QStringList m_szUrls
QStringList m_szIngredients
qreal m_rValues [cIngredient::iIngredientMax]
qint16 m_iLoadedIndex
Additional Inherited Members
Public Types inherited from cInterface
enum iType { iTypeImport = 0, iTypeExport = 1, iTypeDB = 2 }
Defines the type of the interface.
Protected Attributes inherited from cImportInterface
bool m_bLoaded
qint16 m_iLoadedIndex
Member Function Documentation
bool cBleibFitPlugin::config () virtual
Returns
bool
Implements cInterface.
Referenced by pluginType().
QMap< QString, QString > cBleibFitPlugin::detailsCapability () virtual
Returns
QMap<QString, QString>
Implements cImportInterface.
Referenced by pluginType().
QString cBleibFitPlugin::ingredientName () virtual
Returns
QString
Implements cImportInterface.
Referenced by pluginType().
bool cBleibFitPlugin::load (qint16 iIndex) virtual
Parameters
iIndex
Returns
bool
Implements cImportInterface.
References tagMAPPER::key, and tagMAPPER::value.
Referenced by pluginType().
qint16 cBleibFitPlugin::pluginAPIVersion () inline virtual
Returns
qint16
Implements cInterface.
QString cBleibFitPlugin::pluginName () inline virtual
Returns
QString
Implements cInterface.
iType cBleibFitPlugin::pluginType () inline virtual
Returns
iType
Implements cInterface.
References config(), detailsCapability(), ingredientName(), cInterface::iTypeImport, load(), search(), and value().
qint16 cBleibFitPlugin::pluginVersion () inline virtual
Returns
qint16
Implements cInterface.
QStringList cBleibFitPlugin::search (const QString & szSearch, const QString & szDetails = QString("")) virtual
Parameters
szSearch
szDetails
Returns
QStringList
Implements cImportInterface.
References cIngredient::iIngredientMax.
Referenced by pluginType().
qreal cBleibFitPlugin::value (cIngredient::iIngredient i) virtual
Parameters
i
Returns
qreal
Implements cImportInterface.
Referenced by pluginType().
Member Data Documentation
qint16 cBleibFitPlugin::m_iLoadedIndex private
TODO: describe
qreal cBleibFitPlugin::m_rValues[cIngredient::iIngredientMax] private
TODO: describe
QStringList cBleibFitPlugin::m_szIngredients private
TODO: describe
QStringList cBleibFitPlugin::m_szUrls private
TODO: describe
The documentation for this class was generated from the following files:
iBleibFit/cbleibfitplugin.h
iBleibFit/cbleibfitplugin.cpp