Kooky: cConfigDialog Class Reference
cConfigDialog Class Reference
MySQL Database Connector Plugin
Configuration Dialog for dMySQL.
#include <cconfigdialog.h>
Public Member Functions
cConfigDialog (QWidget *parent=0)
~cConfigDialog ()
void setHostname (const QString &szHostname)
void setDatabase (const QString &szDatabase)
void setUserName (const QString &szUserName)
void setPassword (const QString &szPassword)
QString hostname ()
QString database ()
QString userName ()
QString password ()
Private Slots
void on_m_lpTestButton_clicked ()
void on_m_lpPassword_textChanged (const QString &arg1)
void on_m_lpPassword2_textChanged (const QString &arg1)
void on_m_lpOKButton_clicked ()
void on_m_lpCancelButton_clicked ()
Private Attributes
Ui::cConfigDialog * ui
bool m_bPasswordChanged
Detailed Description
This class implements basic import functionality for Kooky. All functions may be overwritten by derriving classes.
Note
Attempts at zen rarely work.
Author
Herwig Birke
Version
1.0
Date
2016/02/09
Constructor & Destructor Documentation
cConfigDialog::cConfigDialog (QWidget * parent = 0) explicit
Parameters
parent
References ui.
cConfigDialog::~cConfigDialog ()
References ui.
Member Function Documentation
QString cConfigDialog::database ()
Returns
QString
References ui.
Referenced by cMySQLPlugin::config().
QString cConfigDialog::hostname ()
Returns
QString
References ui.
Referenced by cMySQLPlugin::config().
void cConfigDialog::on_m_lpCancelButton_clicked () private slot
void cConfigDialog::on_m_lpOKButton_clicked () private slot
References ui.
void cConfigDialog::on_m_lpPassword2_textChanged (const QString & arg1) private slot
Parameters
arg1
References m_bPasswordChanged, and ui.
void cConfigDialog::on_m_lpPassword_textChanged (const QString & arg1) private slot
Parameters
arg1
References m_bPasswordChanged, and ui.
void cConfigDialog::on_m_lpTestButton_clicked () private slot
QString cConfigDialog::password ()
Returns
QString
References ui.
Referenced by cMySQLPlugin::config().
void cConfigDialog::setDatabase (const QString & szDatabase)
Parameters
szDatabase
References ui.
Referenced by cMySQLPlugin::config().
void cConfigDialog::setHostname (const QString & szHostname)
Parameters
szHostname
References ui.
Referenced by cMySQLPlugin::config().
void cConfigDialog::setPassword (const QString & szPassword)
Parameters
szPassword
References ui.
Referenced by cMySQLPlugin::config().
void cConfigDialog::setUserName (const QString & szUserName)
Parameters
szUserName
References ui.
Referenced by cMySQLPlugin::config().
QString cConfigDialog::userName ()
Returns
QString
References ui.
Referenced by cMySQLPlugin::config().
Member Data Documentation
bool cConfigDialog::m_bPasswordChanged private
TODO: describe
Referenced by on_m_lpPassword2_textChanged(), and on_m_lpPassword_textChanged().
Ui::cConfigDialog* cConfigDialog::ui private
TODO: describe
Referenced by cConfigDialog(), database(), hostname(), on_m_lpOKButton_clicked(), on_m_lpPassword2_textChanged(), on_m_lpPassword_textChanged(), password(), setDatabase(), setHostname(), setPassword(), setUserName(), userName(), and ~cConfigDialog().
The documentation for this class was generated from the following files:
dMySQL/cconfigdialog.h
dMySQL/cconfigdialog.cpp