Kooky: cMySQLPlugin Class Reference
cMySQLPlugin Class Reference
MySQL Database Connector Plugin
MySQL Database Connector Plugin class.
#include <cmysqlplugin.h>
Public Member Functions
qint16 pluginAPIVersion ()
Returns the version of the plugin API.
QString pluginName ()
Returns the name of the plugin.
qint16 pluginVersion ()
returns the version of the plugin
iType pluginType ()
returns the type of the plugin.
bool connect ()
connects to the database.
bool init ()
initializes default settings for the plugin.
QString lastError ()
returns the last error string.
bool config ()
calls the configuration dialog.
Public Member Functions inherited from cDBInterface
cDBInterface ()
Constructor.
virtual ~cDBInterface ()
Destructor.
bool connected ()
Returns the current connection status.
QString lastError ()
Returns the last error message of the last operation.
Protected Member Functions
bool open ()
opens the database.
Protected Attributes
QSqlDatabase m_db
QString m_szLastError
Protected Attributes inherited from cDBInterface
bool m_bConnected
Additional Inherited Members
Public Types inherited from cInterface
enum iType { iTypeImport = 0, iTypeExport = 1, iTypeDB = 2 }
Defines the type of the interface.
Detailed Description
This class implements the database connector for MySQL. All functions may be overwritten by derriving classes.
Note
Author
Herwig Birke
Version
1.0
Date
$Date: 2016/02/09
Member Function Documentation
bool cMySQLPlugin::config () virtual
Returns
bool true if the configuration has been changed successfully or false otherwise.
Implements cInterface.
References cConfigDialog::database(), cConfigDialog::hostname(), cDBInterface::m_bConnected, m_db, open(), cConfigDialog::password(), pluginName(), cConfigDialog::setDatabase(), cConfigDialog::setHostname(), cConfigDialog::setPassword(), cConfigDialog::setUserName(), and cConfigDialog::userName().
Referenced by pluginType().
bool cMySQLPlugin::connect () virtual
Returns
bool true on success or false otherwise
Implements cDBInterface.
References m_db, open(), and pluginName().
Referenced by pluginType().
bool cMySQLPlugin::init () virtual
Returns
bool true if settings where successfully tested or false otherwise.
Implements cDBInterface.
References cDBInterface::m_bConnected, m_db, m_szLastError, and pluginName().
Referenced by pluginType().
QString cMySQLPlugin::lastError ()
Returns
QString last error
References m_szLastError.
Referenced by pluginType().
bool cMySQLPlugin::open () protected
Returns
bool true on success or false otherwise.
References cDBInterface::m_bConnected, m_db, and m_szLastError.
Referenced by config(), connect(), and pluginType().
qint16 cMySQLPlugin::pluginAPIVersion () inline virtual
Returns
qint16 plugin API version
Implements cInterface.
QString cMySQLPlugin::pluginName () inline virtual
Returns
QString name of the plugin
Implements cInterface.
Referenced by config(), connect(), and init().
iType cMySQLPlugin::pluginType () inline virtual
Returns
iType type of the plugin.
Returns the type of the plugin. Possible values are:
cInterface::iTypeDB
plugin provides DB connector
cInterface::iTypeExport
plugin provides export capabilities
cInterface::iTypeImport
plugin provides import capabilities
Implements cInterface.
References config(), connect(), init(), cInterface::iTypeDB, lastError(), and open().
qint16 cMySQLPlugin::pluginVersion () inline virtual
Returns
qint16 version of the plugin
Implements cInterface.
Member Data Documentation
QSqlDatabase cMySQLPlugin::m_db protected
holds the database connection
Referenced by config(), connect(), init(), and open().
QString cMySQLPlugin::m_szLastError protected
holds the last error message
Referenced by init(), lastError(), and open().
The documentation for this class was generated from the following files:
dMySQL/cmysqlplugin.h
dMySQL/cmysqlplugin.cpp