Kooky: cImportInterface Class Reference
cImportInterface Class Reference abstract
Kooky Main Program
Interface class for importing data.
#include <cimportinterface.h>
Public Member Functions
cImportInterface ()
virtual QMap< QString, QString > detailsCapability ()=0
virtual QStringList search (const QString &szSearch, const QString &szDetails=QString(""))=0
virtual bool load (qint16 iIndex)=0
bool loaded ()
virtual qreal value (cIngredient::iIngredient i)=0
QString valueStr (cIngredient::iIngredient i)
QString name (cIngredient::iIngredient i)
QString group (cIngredient::iIngredient i)
virtual QString ingredientName ()=0
Public Member Functions inherited from cInterface
virtual qint16 pluginAPIVersion ()=0
Returns the version of the API.
virtual QString pluginName ()=0
Returns the name of the plugin.
virtual qint16 pluginVersion ()=0
Version of the plugin.
virtual iType pluginType ()=0
Returns the type of the plugin.
virtual bool config ()=0
Calls the configuration dialog (if any).
Protected Attributes
bool m_bLoaded
qint16 m_iLoadedIndex
Additional Inherited Members
Public Types inherited from cInterface
enum iType { iTypeImport = 0, iTypeExport = 1, iTypeDB = 2 }
Defines the type of the interface.
Detailed Description
This class implements basic import functionality for Kooky. All functions may be overwritten by derriving classes.
Note
Attempts at zen rarely work.
Author
Herwig Birke
Version
1.0
Date
$Date: 2016/02/09
Constructor & Destructor Documentation
cImportInterface::cImportInterface () inline
References detailsCapability(), load(), and search().
Member Function Documentation
virtual QMap<QString, QString> cImportInterface::detailsCapability () pure virtual
Returns
QMap<QString, QString>
Implemented in cBleibFitPlugin, and cErnaehrungPlugin.
Referenced by cImportInterface().
QString cImportInterface::group (cIngredient::iIngredient i)
Parameters
i
Returns
QString
References cIngredient::group().
Referenced by loaded(), and cImportIngredientDialog::onIngredientListSelectionChanged().
virtual QString cImportInterface::ingredientName () pure virtual
Returns
QString
Implemented in cBleibFitPlugin, and cErnaehrungPlugin.
Referenced by loaded().
virtual bool cImportInterface::load (qint16 iIndex) pure virtual
Parameters
iIndex
Returns
bool
Implemented in cBleibFitPlugin, and cErnaehrungPlugin.
Referenced by cImportInterface(), and cImportIngredientDialog::onIngredientListSelectionChanged().
bool cImportInterface::loaded () inline
Returns
bool
References group(), ingredientName(), m_bLoaded, name(), value(), and valueStr().
QString cImportInterface::name (cIngredient::iIngredient i)
Parameters
i
Returns
QString
References cIngredient::name().
Referenced by loaded(), and cImportIngredientDialog::onIngredientListSelectionChanged().
virtual QStringList cImportInterface::search (const QString & szSearch, const QString & szDetails = QString("")) pure virtual
Parameters
szSearch
szDetails
Returns
QStringList
Implemented in cBleibFitPlugin, and cErnaehrungPlugin.
Referenced by cImportInterface(), and cImportIngredientDialog::on_m_lpSearchButton_clicked().
virtual qreal cImportInterface::value (cIngredient::iIngredient i) pure virtual
Parameters
i
Returns
qreal
Implemented in cBleibFitPlugin, and cErnaehrungPlugin.
Referenced by loaded(), cImportIngredientDialog::onIngredientListSelectionChanged(), and valueStr().
QString cImportInterface::valueStr (cIngredient::iIngredient i)
Parameters
i
Returns
qreal
References cIngredient::iIngredientCalories, cIngredient::iIngredientJoule, and value().
Referenced by loaded(), and cImportIngredientDialog::onIngredientListSelectionChanged().
Member Data Documentation
bool cImportInterface::m_bLoaded protected
TODO: describe
Referenced by loaded().
qint16 cImportInterface::m_iLoadedIndex protected
TODO: describe
The documentation for this class was generated from the following files:
Kooky/cimportinterface.h
Kooky/cimportinterface.cpp